{{- if and .Values.storage.outputs.enabled (not .Values.storage.outputs.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion.fullname" . }}-outputs-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stable-diffusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
    storage-type: outputs
spec:
  accessModes:
    - {{ .Values.storage.outputs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.outputs.size }}
  {{- if .Values.storage.outputs.storageClassName }}
  storageClassName: {{ .Values.storage.outputs.storageClassName }}
  {{- end }}
{{- end }}
