apiVersion: v1
kind: Service
metadata:
  name: {{ include "stable-diffusion.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stable-diffusion.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.uiVariant }}
spec:
  type: {{ include "stable-diffusion.serviceType" . }}
  ports:
  - name: http
    port: {{ include "stable-diffusion.servicePort" . }}
    targetPort: http
    protocol: TCP
    {{- if and (eq (include "stable-diffusion.serviceType" .) "NodePort") (include "stable-diffusion.nodePort" .) }}
    nodePort: {{ include "stable-diffusion.nodePort" . }}
    {{- end }}
  selector:
    {{- include "stable-diffusion.selectorLabels" . | nindent 4 }}
    ui-variant: {{ .Values.uiVariant }}
