apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genai-observability-demo.fullname" . }}-rag101
  labels:
    {{- include "genai-observability-demo.labels" . | nindent 4 }}
    genai: rag101
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "genai-observability-demo.selectorLabels" . | nindent 6 }}
      genai: rag101
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "genai-observability-demo.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        genai: rag101
    spec:
      serviceAccountName: {{ include "genai-observability-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: APP_NAME
            value: Rag101
          - name: OLLAMA_ENDPOINT
            value: {{.Values.ollamaEndpoint}}
          - name: OTLP_ENDPOINT
            value: {{.Values.otlpEndpoint}}
          - name: COLLECT_GPU_STATS
            value: "{{.Values.collectGpuStats}}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
