apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-observability-demo.fullname" . }}-rag101
  labels:
    {{- include "genai-observability-demo.labels" . | nindent 4 }}
    genai: rag101
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "genai-observability-demo.selectorLabels" . | nindent 4 }}
    genai: rag101

