replicaCount: 1

image:
  repository: registry.suse.com/suse/ai-observability-extension
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

prometheus:
  enabled: true
  port: 9090

grafana:
  enabled: true

otlp:
  enabled: true
  endpoint: "http://opentelemetry-collector:4318"

persistence:
  enabled: true
  size: 20Gi
  storageClassName: ""

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "8Gi"

# Advanced configuration
showAdvanced: false
alerting:
  enabled: false
logging:
  level: info
retention:
  days: 30