replicaCount: 1

image:
  repository: python
  tag: "3.11-slim"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

persistence:
  enabled: true
  size: 20Gi
  storageClassName: ""

database:
  type: sqlite
  host: ""
  port: 5432

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

# Advanced configuration
showAdvanced: false
artifactStore:
  type: filesystem
auth:
  enabled: false