apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: {{ .Values.openWebui.service.port }}
    targetPort: {{ .Values.openWebui.service.port }}
  type: {{ .Values.openWebui.service.type }}