apiVersion: v1
kind: Service
metadata:
  name: ollama-chat-app-service
spec:
  selector:
    app: ollama-chat-app
  ports:
  - protocol: TCP
    port: {{ .Values.llmChat.service.port }}
    targetPort: {{ .Values.llmChat.service.port }}
  type: {{ .Values.llmChat.service.type }}