{{- if .Values.litellm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-ai-ollama.fullname" . }}-litellm-masterkey
  labels:
    {{- include "rancher-ai-ollama.labels" . | nindent 4 }}
type: Opaque
stringData:
  masterkey: {{ include "rancher-ai-ollama.litellmMasterKey" . | quote }}
{{- end }}
