apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-ai-ollama.fullname" . }}-litellm
  labels:
    {{- include "rancher-ai-ollama.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
spec:
  type: {{ .Values.litellm.service.type }}
  {{- if eq .Values.litellm.service.type "LoadBalancer" }}
  {{- with .Values.litellm.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.litellm.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.litellm.service.type "NodePort") (.Values.litellm.service.nodePort) }}
    nodePort: {{ .Values.litellm.service.nodePort }}
    {{- end }}
  selector:
    app: litellm
    release: {{ .Release.Name }}
