# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: ollama
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ollama-pvc
      {{- else }}
      volumes:
        - name: ollama-models
          emptyDir: {}
      {{- end }}
      initContainers:
        - name: pull-models
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              OLLAMA_HOST="127.0.0.1:11434" ollama serve &
              SERVER_PID=$!
              echo "Waiting for Ollama server to start..."
              sleep 5
              
              MODELS=$(echo "{{ .Values.models.pull }}" | tr "," "\n")
              for model in $MODELS
              do
                echo "Pulling model: $model"
                ollama pull "$model"
              done
              
              echo "Model pulling complete. Stopping server."
              kill $SERVER_PID
              wait $SERVER_PID
          volumeMounts:
            - name: ollama-models
              mountPath: {{ .Values.persistence.mountPath }}
      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
            - name: OLLAMA_KEEP_ALIVE
              value: {{ .Values.ollama.keep_alive | quote }}
            - name: OLLAMA_NUM_PARALLEL
              value: {{ .Values.ollama.num_parallel | quote }}
            - name: OLLAMA_MAX_LOADED_MODELS
              value: {{ .Values.ollama.max_loaded_models | quote }}
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: ollama-models
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
