apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: {{ .Values.ollama.service.port }}
    targetPort: {{ .Values.ollama.service.port }}
  type: {{ .Values.ollama.service.type }}