apiVersion: v1
kind: Service
metadata:
  name: ollama-chat-app-service
spec:
  selector:
    app: ollama-chat-app
  ports:
  - protocol: TCP
    port: {{ .Values.llmChat.service.port }}
    targetPort: {{ .Values.llmChat.service.port }}
    name: http
  {{- if .Values.llmChat.devMode.enabled }}
  - protocol: TCP
    port: {{ .Values.llmChat.devMode.sshPort }}
    targetPort: {{ .Values.llmChat.devMode.sshPort }}
    name: ssh
  {{- end }}
  type: {{ .Values.llmChat.service.type }}