# Default values for the chart

# -- Global image pull policy
imagePullPolicy: IfNotPresent
# -- Default pull secrets (can be overridden, e.g., for SUSE chart)
imagePullSecrets: []
# -- Application settings
ollama:
  image:
    repository: ollama/ollama
    tag: "0.6.8"
  service:
    port: 11434
    type: ClusterIP
  # -- Hardware Configuration for Ollama
  hardware:
    type: "nvidia" # Options: "nvidia", "apple"
  gpu:
    enabled: false
  # -- Resource allocation for the main Ollama container
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: "" # Use default if empty, or specify a storage class
openWebui:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "0.6.9"
  service:
    port: 8080
    type: NodePort
llmChat:
  image:
    repository: ghcr.io/suse-technical-marketing/suse-ai-demo
    tag: "07d4d6f"
  service:
    port: 7860
    type: NodePort
  devMode:
    enabled: false
    image:
      repository: ghcr.io/suse-technical-marketing/suse-ai-demo-dev # This will be the new dev image
      tag: "latest-dev" # This will be the new dev image tag
    persistence:
      enabled: false
      size: 1Gi
      storageClassName: "" # Use default if empty, or specify a storage class
    sshPort: 22 # Default SSH port
    gitRepo: "https://github.com/suse-technical-marketing/suse-ai-demo.git" # Default git repo for initial clone
    gitBranch: "main" # Default branch to clone
