replicaCount: 1

image:
  repository: registry.suse.com/suse/ai-deployer
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

config:
  namespace: default
  registry: registry.suse.com

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

# Advanced configuration
showAdvanced: false
rbac:
  enabled: true
serviceAccount:
  create: true
webhook:
  enabled: false