apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "comfyui-video-lab.fullname" . }}-manifest
  labels:
    {{- include "comfyui-video-lab.labels" . | nindent 4 }}
data:
  manifest.txt: |
    {{- include "comfyui-video-lab.modelManifest" . | nindent 4 }}
