name: Auto Version Bump Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  auto-version-bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install yq (YAML processor)
        uses: mikefarah/yq@master

      - name: Detect changed charts and bump versions
        run: |
          # Get list of changed files since last commit
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          
          # Extract unique chart directories that have changes
          CHANGED_CHARTS=$(echo "$CHANGED_FILES" | grep '^charts/' | cut -d'/' -f1-2 | sort -u)
          
          echo "Changed charts detected:"
          echo "$CHANGED_CHARTS"
          
          # Flag to track if any versions were bumped
          VERSION_BUMPED=false
          
          # Process each changed chart
          for CHART_DIR in $CHANGED_CHARTS; do
            if [ -f "$CHART_DIR/Chart.yaml" ]; then
              echo "Processing chart: $CHART_DIR"
              
              # Get current version
              CURRENT_VERSION=$(yq eval '.version' "$CHART_DIR/Chart.yaml")
              echo "Current version: $CURRENT_VERSION"
              
              # Split version into parts (assuming semantic versioning)
              IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
              
              # Increment patch version
              NEW_PATCH=$((PATCH + 1))
              NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
              
              echo "Bumping version from $CURRENT_VERSION to $NEW_VERSION"
              
              # Update Chart.yaml with new version
              yq eval ".version = \"$NEW_VERSION\"" -i "$CHART_DIR/Chart.yaml"
              
              # Stage the file
              git add "$CHART_DIR/Chart.yaml"
              
              VERSION_BUMPED=true
            else
              echo "No Chart.yaml found in $CHART_DIR, skipping..."
            fi
          done
          
          # Commit and push if any versions were bumped
          if [ "$VERSION_BUMPED" = true ]; then
            echo "Committing version bumps..."
            git commit -m "🤖 Auto-bump chart versions

🚀 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            
            git push
            echo "Version bumps pushed successfully!"
          else
            echo "No chart versions needed bumping."
          fi